# Generated by Django 5.1 on 2025-01-14 20:57
# FIXED: Skip both RenameField (bio) and RemoveField (birth_date) as neither column exists

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_userprofile'),
    ]

    operations = [
        # Skip both operations - columns don't exist in the actual database
        # migrations.RenameField(
        #     model_name='userprofile',
        #     old_name='bio',
        #     new_name='bookedJob',
        # ),
        # migrations.RemoveField(
        #     model_name='userprofile',
        #     name='birth_date',
        # ),
        migrations.AddField(
            model_name='userprofile',
            name='bookedJob',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bookedRental',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferredJobs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferredRentals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
