# Generated by Django 5.1 on 2025-01-25 14:24
# RESTORED with proper CreateModel to fix KeyError

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_rename_bio_userprofile_bookedjob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnRentals',
            fields=[
                ('id', models.TextField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('balcony', models.TextField(blank=True, null=True)),
                ('bath', models.TextField(blank=True, null=True)),
                ('bed', models.TextField(blank=True, null=True)),
                ('block_size', models.TextField(blank=True, null=True)),
                ('built', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=50)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('deposit', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('floor', models.TextField(blank=True, null=True)),
                ('furnished', models.TextField(blank=True, null=True)),
                ('fees', models.TextField(blank=True, null=True)),
                ('garden', models.TextField(blank=True, null=True)),
                ('gps_lat', models.TextField(blank=True, null=True)),
                ('gps_lon', models.TextField(blank=True, null=True)),
                ('gym', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('imageList', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('max_floor', models.TextField(blank=True, null=True)),
                ('max_tenant', models.TextField(blank=True, null=True)),
                ('paid', models.TextField(blank=True, null=True)),
                ('parking', models.TextField(blank=True, null=True)),
                ('pets', models.TextField(blank=True, null=True)),
                ('pool', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('score', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('size_unit', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('clusterCity', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]


