# Generated by Django 5.1 on 2025-01-25 14:35
# RESTORED with proper CreateModel to fix KeyError

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_ownrentals'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnJobs',
            fields=[
                ('id', models.TextField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('certification', models.TextField(blank=True, null=True)),
                ('jobType', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('loceJobTagModel', models.TextField(blank=True, null=True)),
                ('station', models.TextField(blank=True, null=True)),
                ('normTitle', models.TextField(blank=True, null=True)),
                ('companyRating', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('paid', models.TextField(blank=True, null=True)),
                ('gps_lat', models.TextField(blank=True, null=True)),
                ('gps_lon', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('recScore', models.TextField(blank=True, null=True)),
                ('recDescription', models.TextField(blank=True, null=True)),
                ('postcode', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('companyLogoUrl', models.TextField(blank=True, null=True)),
                ('clusterCity', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]


