# Generated by Django 5.1 on 2025-02-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_alter_ownrentals_affscore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownrentals',
            name='affScore',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='affScore',
            field=models.TextField(blank=True, null=True),
        ),
    ]
