# Generated by Django 5.1 on 2025-02-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_alter_ownrentals_affscore_alter_rentals_affscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownrentals',
            name='bath',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownrentals',
            name='bed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownrentals',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownrentals',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='bath',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='bed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
