# Generated by Django 5.1 on 2025-02-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_alter_jobs_gps_lat_alter_jobs_gps_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownrentals',
            name='security',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownrentals',
            name='securityRank',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='security',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='securityRank',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
