# Generated by Django 5.1 on 2025-03-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_ownrentals_security_ownrentals_securityrank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(editable=False)),
                ('county', models.TextField(editable=False)),
                ('state', models.TextField(editable=False)),
                ('city', models.TextField(editable=False)),
                ('geometry', models.TextField(editable=False)),
                ('properties', models.TextField(editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='cities',
            name='Climate',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='CoL',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='Inhabitants',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='PP',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='QoL',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='Secirity',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='Temperatures',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='apartmentPrice',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='avgNetSalary',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='clothing',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='commuteTime',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='dailyFood',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='entert',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='gps_lat',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='gps_lon',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='grossRentalYield',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='health',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='incomeAverage',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='loanAffordability',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='markets',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='mortgage2Income',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='pollution',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='ppi',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='price2Income',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='price2RentCentre',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='price2RentOutside',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='property2Income',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='rentalAverage',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='rentalFee',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='restaurants',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='safety',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='school',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='sportsnLeisure',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='utilities',
        ),
    ]
