# Generated by Django 5.1 on 2025-03-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0015_alter_companies_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
    ]
