# Generated by Django 5.1 on 2025-03-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0017_companies_admin_companies_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='subsidiaries',
            field=models.TextField(blank=True, null=True),
        ),
    ]
