# Generated by Django 5.1 on 2025-03-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0018_companies_subsidiaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownrentals',
            name='locationRank',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='locationRank',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
