# Generated by Django 5.1 on 2025-04-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0019_ownrentals_locationrank_rentals_locationrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownrentals',
            name='referenceCircle',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='referenceCircle',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
