# Generated by Django 5.1 on 2025-04-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0023_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='scenarioHistory',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
