# Generated by Django 5.1 on 2025-04-11 14:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0024_userhistory_scenariohistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhistory',
            old_name='scenarioHistory',
            new_name='scenarios',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='jobHistory',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='rentalHistory',
        ),
        migrations.AddField(
            model_name='userhistory',
            name='jobs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='rentals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
