# Generated by Django 5.1 on 2025-04-12 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0025_rename_scenariohistory_userhistory_scenarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownrentals',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rentals',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ownjobs',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
