# Generated by Django 5.1 on 2025-04-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0026_ownrentals_date_rentals_date_alter_jobs_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='clusterCity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownjobs',
            name='clusterCity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownrentals',
            name='clusterCity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='clusterCity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
