# Generated by Django 5.1 on 2025-04-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0029_alter_ownrentals_referencecircle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownrentals',
            name='locationRank',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ownrentals',
            name='referenceCircle',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='locationRank',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='referenceCircle',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
