# Generated by Django 5.1 on 2025-04-18 13:30
# FIXED: img_url doesn't exist; imageList already in schema from 0004

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0031_alter_ownrentals_date_alter_rentals_date'),
    ]

    operations = [
        # Skip RenameField - both imageList already present and img_url doesn't exist
        # migrations.RenameField(
        #     model_name='ownrentals',
        #     old_name='img_url',
        #     new_name='imageList',
        # ),
        # migrations.RenameField(
        #     model_name='rentals',
        #     old_name='img_url',
        #     new_name='imageList',
        # ),
    ]

