# Generated by Django 5.1 on 2025-10-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0033_jobs_address_ownjobs_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='bbox',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='clusterCount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
