# Generated by Django 4.2.14 on 2024-08-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.TextField()),
                ('furnished', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('bath', models.FloatField()),
                ('currency', models.TextField()),
                ('fees', models.IntegerField()),
                ('block_size', models.IntegerField()),
                ('balcony', models.IntegerField()),
                ('city', models.TextField()),
                ('built', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
                ('area', models.TextField()),
                ('max_floor', models.IntegerField()),
                ('size_unit', models.IntegerField()),
                ('max_tenant', models.IntegerField()),
                ('location', models.TextField()),
                ('pets', models.BooleanField()),
                ('size', models.IntegerField()),
                ('type', models.TextField()),
                ('price', models.IntegerField()),
                ('gps_lat', models.FloatField()),
                ('garden', models.BooleanField()),
                ('gym', models.BooleanField()),
                ('paid', models.TextField()),
                ('gps_lon', models.FloatField()),
                ('link', models.TextField()),
                ('address', models.TextField()),
                ('score', models.IntegerField()),
                ('pool', models.BooleanField()),
                ('desc', models.TextField()),
                ('url', models.TextField()),
                ('age', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('bed', models.FloatField()),
                ('deposit', models.IntegerField()),
            ],
        ),
    ]
