# Generated by Django 4.2.14 on 2024-08-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='paid',
            field=models.BooleanField(),
        ),
    ]
