# Generated by Django 4.2.14 on 2024-08-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_rentals_city_alter_rentals_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='img_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='id',
            field=models.TextField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='paid',
            field=models.TextField(),
        ),
    ]
