# Generated by Django 5.0.7 on 2024-08-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_rename_img_rentals_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='block_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='fees',
            field=models.TextField(blank=True, null=True),
        ),
    ]
