# Generated by Django 5.0.7 on 2024-08-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_remove_rentals_date_rentals_furnished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='balcony',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='furnished',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='garden',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='gym',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='parking',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='pets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='pool',
            field=models.TextField(blank=True, null=True),
        ),
    ]
