# Generated by Django 5.0.7 on 2024-08-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_alter_rentals_age_alter_rentals_bath_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentals',
            name='fees',
        ),
    ]
