# Generated by Django 5.1 on 2024-08-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0020_rename_img_rentals_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.TextField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('segment', models.TextField(blank=True, null=True)),
                ('salary', models.TextField(blank=True, null=True)),
                ('paid', models.TextField(blank=True, null=True)),
                ('gps_lat', models.TextField(blank=True, null=True)),
                ('gps_lon', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('Date', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rentals',
            name='bed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='gps_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
