# Generated by Django 5.1 on 2024-08-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0023_rentals_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentals',
            name='img',
        ),
    ]
