# Generated by Django 5.1 on 2024-08-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0024_remove_rentals_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.TextField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('gps_lat', models.TextField(blank=True, null=True)),
                ('gps_lon', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('HQAddr', models.TextField(blank=True, null=True)),
                ('locAddr', models.TextField(blank=True, null=True)),
                ('reviews', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='Climate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='CoL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Inhabitants',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='PP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='QoL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Secirity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Temperatures',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='dailyFood',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='entert',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='incomeAverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='rentalAverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='rentalFee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='school',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='travel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='utilities',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='gps_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
