# Generated by Django 5.1 on 2024-08-31 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0025_companies_cities_climate_cities_col_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companies',
        ),
    ]
