# Generated by Django 5.1 on 2024-08-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0027_companies_alter_jobs_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='company',
            field=models.TextField(blank=True, null=True),
        ),
    ]
