# Generated by Django 5.1 on 2024-08-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0031_rename_name_companies_compname_remove_jobs_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='companyID',
        ),
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.TextField(blank=True, null=True),
        ),
    ]
