# Generated by Django 5.1 on 2024-08-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0033_rename_compname_companies_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='company',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
