# Generated by Django 4.2.14 on 2024-08-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app','0037_alter_jobs_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.TextField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('segment', models.TextField(blank=True, null=True)),
                ('salary', models.TextField(blank=True, null=True)),
                ('paid', models.TextField(blank=True, null=True)),
                ('gps_lat', models.TextField(blank=True, null=True)),
                ('gps_lon', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('Date', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
