# Generated by Django 5.1 on 2024-08-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0039_rename_segment_jobs_sector_alter_jobs_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
