# Generated by Django 5.1 on 2024-09-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0041_rename_description_jobs_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='timezone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
