# Generated by Django 5.1 on 2024-09-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0046_rentals_green_rentals_greenrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='pollutionRank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
