# Generated by Django 5.1 on 2024-10-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0050_cities_apartmentprice_cities_clothing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='ApartmentPrice',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='Clothing',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='CommuteTime',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='GrossRentalYield',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='Health',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='LoanAffordability',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='Markets',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='Mortgage2Income',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='Pollution',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='Price2Income',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='Price2RentCentre',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='Price2RentOutside',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='Property2Income',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='RentalFee',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='Restaurants',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='Safety',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='SportsnLeisure',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='Transportation',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='Utilities',
        ),
        migrations.AlterField(
            model_name='cities',
            name='CoL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='ppi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='apartmentPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='clothing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='commuteTime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='grossRentalYield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='health',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='loanAffordability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='markets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='mortgage2Income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='pollution',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='price2Income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='price2RentCentre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='price2RentOutside',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='property2Income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='restaurants',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='safety',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='sportsnLeisure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='transportation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
