# Generated by Django 5.1 on 2024-10-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0051_remove_cities_apartmentprice_remove_cities_clothing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='apartmentPrice',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='clothing',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='commuteTime',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='grossRentalYield',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='health',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='loanAffordability',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='markets',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='mortgage2Income',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='pollution',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='ppi',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='price2Income',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='price2RentCentre',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='price2RentOutside',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='property2Income',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='restaurants',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='safety',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='sportsnLeisure',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='transportation',
        ),
    ]
