# Generated by Django 5.1 on 2024-10-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0055_jobs_recdescription_jobs_recscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='affDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='affScore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
