# Generated by Django 5.1 on 2024-10-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0059_remove_appdata_googapikey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdata',
            name='GoogApiKey',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appdata',
            name='mapBoxAccessToken',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
    ]
