# Generated by Django 5.1 on 2024-11-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0065_remove_jobs_companylogourl_alter_jobs_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='companyLogoUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
