# Generated by Django 5.1 on 2024-11-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0067_remove_jobs_companylogourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='companyLogoUrl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
