# Generated by Django 5.1 on 2024-11-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0071_alter_rentals_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='companyLogoUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
