# Generated by Django 5.1 on 2024-11-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0076_alter_rentals_culture_alter_rentals_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='affScore',
            field=models.TextField(blank=True, null=True),
        ),
    ]
