# Generated by Django 5.1 on 2024-12-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0079_delete_companies_remove_rentals_imagelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='nearbyRestaurants',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentals',
            name='nearbyRestaurantsUpdated',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
