# Generated by Django 5.0.7 on 2024-08-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_alter_rentals_address_alter_rentals_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentals',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='rentals',
            old_name='img_url',
            new_name='imageList',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='age',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='block_size',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='link',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='location',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='max_floor',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='max_tenant',
        ),
        migrations.AddField(
            model_name='rentals',
            name='date',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='rentals',
            name='relDate',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
