# Generated by Django 5.0.7 on 2024-08-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_rentals_block_size_rentals_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentals',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='rentals',
            old_name='imageList',
            new_name='img_url',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='furnished',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='relDate',
        ),
        migrations.AddField(
            model_name='rentals',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='deposit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='max_floor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='max_tenant',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='fees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
