# Generated by Django 5.0.7 on 2024-08-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_rename_image_rentals_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentals',
            name='date',
        ),
        migrations.AddField(
            model_name='rentals',
            name='furnished',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
