# Generated by Django 5.0.7 on 2024-08-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_remove_rentals_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='fees',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
