# Generated by Django 5.0.7 on 2024-08-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_rentals_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentals',
            name='fees',
        ),
    ]
