# Generated by Django 5.1 on 2024-08-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0016_rentals_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('gps_lat', models.TextField(blank=True, null=True)),
                ('gps_lon', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rentals',
            name='bath',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='bed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='block_size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='built',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='fees',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='gps_lat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='gps_lon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='max_floor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='max_tenant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='size_unit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
