# Generated by Django 5.1 on 2024-08-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0017_cities_alter_rentals_bath_alter_rentals_bed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='imageList',
            field=models.TextField(blank=True, null=True),
        ),
    ]
