# Generated by Django 5.1 on 2024-08-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0018_rentals_imagelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentals',
            name='imageList',
        ),
    ]
