# Generated by Django 5.1 on 2024-08-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0019_remove_rentals_imagelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentals',
            old_name='img',
            new_name='image',
        ),
    ]
