# Generated by Django 5.1 on 2024-08-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0021_jobs_alter_rentals_bed_alter_rentals_gps_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='id',
        ),
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.TextField(default='none', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
