# Generated by Django 5.1 on 2024-08-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0022_remove_cities_id_alter_cities_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
