# Generated by Django 5.1 on 2024-08-31 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0026_delete_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.TextField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('gps_lat', models.TextField(blank=True, null=True)),
                ('gps_lon', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('HQAddr', models.TextField(blank=True, null=True)),
                ('locAddr', models.TextField(blank=True, null=True)),
                ('reviews', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='core_app.companies'),
        ),
    ]
