# Generated by Django 5.1 on 2024-08-31 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0028_alter_jobs_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companies',
        ),
    ]
