# Generated by Django 5.1 on 2024-08-31 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0030_companies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='name',
            new_name='compName',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='company',
        ),
        migrations.AddField(
            model_name='jobs',
            name='companyID',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='name', to='core_app.companies'),
            preserve_default=False,
        ),
    ]
