# Generated by Django 5.1 on 2024-08-31 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0032_remove_jobs_companyid_jobs_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='compName',
            new_name='name',
        ),
    ]
