# Generated by Django 5.1 on 2024-08-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0038_recreate_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='segment',
            new_name='sector',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
