# Generated by Django 5.1 on 2024-08-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0040_jobs_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='description',
            new_name='desc',
        ),
    ]
