# Generated by Django 5.1 on 2024-09-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0042_cities_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='nearbyRestaurants',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='nearbyRestaurantsUpdated',
            field=models.TextField(blank=True, null=True),
        ),
    ]
