# Generated by Django 5.1 on 2024-09-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0043_rentals_nearbyrestaurants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='pollution',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
