# Generated by Django 5.1 on 2024-09-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0044_rentals_pollution'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='culture',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='cultureRank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='education',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='educationRank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='entertain',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='entertainRank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='goOut',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='goOutRank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='health',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='healthRank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='housing',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='housingRank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='shoping',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='shopingRank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='sports',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='sportsRank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='travel',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='travelRank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='turism',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='turismRank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
