# Generated by Django 5.1 on 2024-09-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0045_rentals_culture_rentals_culturerank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='green',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='greenRank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
