# Generated by Django 5.1 on 2024-09-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0047_rentals_pollutionrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='gptDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
