# Generated by Django 5.1 on 2024-09-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0048_rentals_gptdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='bed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='gps_lat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='gps_lon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
