# Generated by Django 5.1 on 2024-10-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0049_alter_rentals_bed_alter_rentals_gps_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='ApartmentPrice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Clothing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='CommuteTime',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='GrossRentalYield',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Health',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='LoanAffordability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Markets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Mortgage2Income',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Pollution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Price2Income',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Price2RentCentre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Price2RentOutside',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Property2Income',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='RentalFee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Restaurants',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Safety',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='SportsnLeisure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Transportation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Utilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='ppi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='CoL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
