# Generated by Django 5.1 on 2024-10-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0052_remove_cities_apartmentprice_remove_cities_clothing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='apartmentPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='clothing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='commuteTime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='grossRentalYield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='health',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='loanAffordability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='markets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='mortgage2Income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='pollution',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='ppi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='price2Income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='price2RentCentre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='price2RentOutside',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='property2Income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='restaurants',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='safety',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='sportsnLeisure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='transportation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
