# Generated by Django 5.1 on 2024-10-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0053_cities_apartmentprice_cities_clothing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='avgNetSalary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
