# Generated by Django 5.1 on 2024-10-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0054_cities_avgnetsalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='recDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='recScore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
