# Generated by Django 5.1 on 2024-10-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0056_rentals_affdescription_rentals_affscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapBoxAccessToken', models.TextField(editable=False)),
                ('GoogApiKey', models.TextField(editable=False)),
            ],
        ),
    ]
