# Generated by Django 5.1 on 2024-10-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0057_appdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdata',
            name='key',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appdata',
            name='name',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
    ]
