# Generated by Django 5.1 on 2024-10-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0058_appdata_key_appdata_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appdata',
            name='GoogApiKey',
        ),
        migrations.RemoveField(
            model_name='appdata',
            name='mapBoxAccessToken',
        ),
    ]
