# Generated by Django 5.1 on 2024-11-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0061_remove_appdata_googapikey_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='Date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='jobs',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
