# Generated by Django 5.1 on 2024-11-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0063_jobs_area_jobs_certification_jobs_companyrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='companyLogoUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
