# Generated by Django 5.1 on 2024-11-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0066_jobs_companylogourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='companyLogoUrl',
        ),
    ]
