# Generated by Django 5.1 on 2024-11-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0068_jobs_companylogourl_alter_jobs_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='companyLogoUrl',
        ),
    ]
