# Generated by Django 5.1 on 2024-11-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0069_remove_jobs_companylogourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='recScore',
            field=models.TextField(blank=True, null=True),
        ),
    ]
