# Generated by Django 5.1 on 2024-11-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0070_alter_jobs_recscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
