# Generated by Django 5.1 on 2024-11-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0077_alter_rentals_affscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='imageList',
            field=models.TextField(blank=True, null=True),
        ),
    ]
