# Generated by Django 5.1 on 2024-12-04 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0078_rentals_imagelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companies',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='imageList',
        ),
    ]
