# Generated by Django 5.1 on 2024-12-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0080_alter_rentals_nearbyrestaurants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.TextField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('gps_lat', models.TextField(blank=True, null=True)),
                ('gps_lon', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('HQAddr', models.TextField(blank=True, null=True)),
                ('locAddr', models.TextField(blank=True, null=True)),
                ('reviews', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rentals',
            name='nearbyRestaurants',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='nearbyRestaurantsUpdated',
            field=models.TextField(blank=True, null=True),
        ),
    ]
