# Generated by Django 5.1 on 2025-02-09 11:07
# FIXED: Only remove fields that were actually created

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_ownjobs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        # Only remove these fields if they exist (they were added in 0003)
        migrations.RemoveField(
            model_name='userprofile',
            name='bookedJob',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bookedRental',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferredJobs',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferredRentals',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        # Skip AddField user_ptr - already exists
    ]
