# Generated by Django 5.1 on 2025-02-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        # affScore and rank fields did not exist on OwnRentals in 0004, so use AddField
        migrations.AddField(
            model_name='ownrentals',
            name='affScore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownrentals',
            name='cultureRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownrentals',
            name='educationRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownrentals',
            name='entertainRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownrentals',
            name='goOutRank',
            field=models.FloatField(blank=True, null=True),
        ),
        # gps_lat and gps_lon exist as TextField in 0004, so AlterField is correct
        migrations.AlterField(
            model_name='ownrentals',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownrentals',
            name='gps_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownrentals',
            name='greenRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownrentals',
            name='healthRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownrentals',
            name='housingRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownrentals',
            name='pollutionRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownrentals',
            name='shopingRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownrentals',
            name='sportsRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownrentals',
            name='travelRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownrentals',
            name='turismRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='affScore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='cultureRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='educationRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='entertainRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='goOutRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='gps_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='greenRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='healthRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='housingRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='pollutionRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='shopingRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='sportsRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='travelRank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='turismRank',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
