# Generated by Django 5.1 on 2025-02-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_alter_ownrentals_bath_alter_ownrentals_bed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='gps_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownjobs',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownjobs',
            name='gps_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
