# Generated by Django 5.1 on 2025-03-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_security_remove_cities_climate_remove_cities_col_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='Climate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='CoL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Inhabitants',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='PP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='QoL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Secirity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='Temperatures',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='apartmentPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='avgNetSalary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='clothing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='commuteTime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='dailyFood',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='entert',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='gps_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='grossRentalYield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='health',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='incomeAverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='loanAffordability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='markets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='mortgage2Income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='pollution',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='ppi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='price2Income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='price2RentCentre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='price2RentOutside',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='property2Income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='rentalAverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='rentalFee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='restaurants',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='safety',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='school',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='sportsnLeisure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='timezone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='transportation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='travel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='utilities',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
