# Generated by Django 5.1 on 2025-03-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_cities_climate_cities_col_cities_inhabitants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
