# Generated by Django 5.1 on 2025-03-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0016_companies_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='sector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
