# Generated by Django 5.1 on 2025-04-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0020_ownrentals_referencecircle_rentals_referencecircle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='jobHistory',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rentalHistory',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
