# Generated by Django 5.1 on 2025-04-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0027_jobs_clustercity_ownjobs_clustercity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownrentals',
            name='locationRank',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='locationRank',
            field=models.TextField(blank=True, null=True),
        ),
    ]
