# Generated by Django 5.1 on 2025-04-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0028_alter_ownrentals_locationrank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownrentals',
            name='referenceCircle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='referenceCircle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
