# Generated by Django 5.1 on 2025-04-15 22:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0030_alter_ownrentals_locationrank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownrentals',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
