# Generated by Django 5.1 on 2025-04-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0032_rename_img_url_ownrentals_imagelist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownjobs',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
