# Generated by Django 5.1 on 2026-03-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0034_cities_bbox_cities_clustercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='rentalPriceContours',
            field=models.JSONField(blank=True, null=True),
        ),
    ]