# Generated by Django 5.1 on 2026-03-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0035_cities_rentalpricecontours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='gps_lat',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='gps_lon',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='gps_lat',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='gps_lon',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownjobs',
            name='gps_lat',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownjobs',
            name='gps_lon',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownrentals',
            name='gps_lat',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownrentals',
            name='gps_lon',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='gps_lat',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='gps_lon',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
